In [1]:
import numpy as np

In [ ]:
# 계단함수 구현(부동소수점)
def step_function(x):
    if x > 0:
        return 1
    else:
        return 0

In [ ]:
# 계단함수 구현(numpy 입력)
def step_function(x):
    if x > 0:
        return x.astype(int)

In [2]:
# sigmoid 함수
def sigmoid_function(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
def ReLU(x):
    return max(0, x)

In [15]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(X.shape)
print(W1.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
print(A1)

(2,)
(2, 3)
(3,)
[0.3 0.7 1.1]


In [ ]:

# 은닉층 1개 통과 
Z1 = sigmoid_function(A1)


In [17]:
print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [4]:
#  전체 신경망 구현(3개층)
import numpy as np

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['B1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['B2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3],[0.2, 0.4]])
    network['B3'] = np.array([0.1, 0.2])

    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['B1'], network['B2'], network['B3']

    # 첫번째 층
    A1 = np.dot(x, W1) + b1
    Z1 = sigmoid_function(A1)

    # 두번째 층
    A2 = np.dot(Z1, W2) + b2
    Z2 = sigmoid_function(A2)

    # 세번째 층
    A3 = np.dot(Z2, W3) + b3
    

    return A3



network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
